### ISSUE TITLE
Training with CPU mode

### ISSUE THREAD

**Issue by Arroosh** [taylorlu/Speaker-Diarization#11]
/home/sm/venv/lib/python3.6/site-packages/torch/cuda/__init__.py:118: UserWarning: 
    Found GPU0 Quadro K4200 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    The minimum cuda capability that we support is 3.5.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    main()
  File "train.py", line 86, in main
    diarization_experiment(model_args, training_args, inference_args)
  File "train.py", line 44, in diarization_experiment
    model = uisrnn.UISRNN(model_args)
  File "/home/sm/Speaker-Diarization/uisrnn/uisrnn.py", line 99, in __init__
    sigma2 * torch.ones(self.observation_dim).to(self.device))
RuntimeError: CUDA error: no kernel image is available for execution on the device

Can anyone suggest me any alternative to perform training?
Thanks in advance

**Comment by Arroosh** [comment]
Resolved by changing line 86 of uisrnn.py
self.device = torch.device(
        'cuda:0' if torch.cuda.is_available() else 'cpu')
 to
    self.device = torch.device('cpu')
